version: "3.8"
services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: "user"
      POSTGRES_USER: "user"
      POSTGRES_DB: "example"
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d